<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CK.AppIdentity.Hosting" Version="0.14.1" />
    <PackageReference Include="CK.Cris.AspNet" Version="0.55.3--ci.1" />
    <PackageReference Include="CK.Cris.Auth" Version="0.43.2--ci.1" />
    <PackageReference Include="CK.DB.AspNet.Auth" Version="31.0.3--ci.5" />
    <PackageReference Include="CK.DB.User.UserPassword" Version="28.0.3--ci.5" />
    <PackageReference Include="CK.Ng.AspNet.Auth.Basic" Version="0.31.3--ci.7" />
    <PackageReference Include="CK.Ng.Zorro.BackOffice" Version="0.7.0--ci.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CK.DB.SiteMap\CK.DB.SiteMap.csproj" />
    <ProjectReference Include="..\..\CK.IO.SiteMap\CK.IO.SiteMap.csproj" />
    <ProjectReference Include="..\..\CK.Ng.SiteMap\CK.Ng.SiteMap.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.sql" />
    <EmbeddedResource Include="**\*.tql" />
    <None Remove="**\*.sql" />
    <None Remove="**\*.sql" />
  </ItemGroup>

</Project>
