<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.IO.Auth" Version="0.0.0--05it0jf-develop" />
    <PackageReference Include="CK.Cris.TypeScript" Version="0.50.0-a00-00-0012-develop" />
  </ItemGroup>
</Project>