<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.IO.Auth" Version="0.38.1--0004-develop" />
    <PackageReference Include="CK.Cris.TypeScript" Version="0.38.1--0004-develop" />
  </ItemGroup>
</Project>