<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>False</IsPackable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.Testing.Nunit" Version="12.1.0" />
        <PackageReference Include="CK.TS.Angular.Engine" Version="0.0.0--05fwv2h-explo" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="CK.Testing.SqlServerEngine" Version="29.1.1--0000-develop" />
        <PackageReference Include="CK.Testing.TypeScriptEngine" Version="0.0.0--05fwv2h-explo" />
        <PackageReference Include="CK.Testing.AspNetServer.Auth" Version="26.1.0" />
        <PackageReference Include="CK.Cris.AspNet.Engine" Version="0.0.0--05fy9b3-explo" />
        <PackageReference Include="CK.Ng.AspNet.Auth.Basic" Version="0.0.0--05fwv2h-explo" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CK.Ng.SiteMap\CK.Ng.SiteMap.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="TSInlineTests\" />
    </ItemGroup>

</Project>