<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>False</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Testing.Nunit" Version="14.1.0" />
    <PackageReference Include="CK.TS.Angular.Engine" Version="0.30.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
    <PackageReference Include="CK.Testing.SqlServerEngine" Version="32.1.1" />
    <PackageReference Include="CK.Testing.TypeScriptEngine" Version="0.30.1" />
    <PackageReference Include="CK.Testing.AspNetServer.Auth" Version="29.1.1" />
    <PackageReference Include="CK.Cris.AspNet.Engine" Version="0.54.1" />
    <PackageReference Include="CK.Ng.AspNet.Auth.Basic" Version="0.30.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.Ng.SiteMap\CK.Ng.SiteMap.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="TSInlineTests\" />
  </ItemGroup>
</Project>