<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.HWorkspace.Page" Version="0.13.0--ci.5" />
    <PackageReference Include="CK.SqlServer.Dapper" Version="15.0.0--ci.9" />
    <PackageReference Include="CK.Ng.AspNet.Auth" Version="0.31.0--ci.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.IO.Ng.SiteMap\CK.IO.Ng.SiteMap.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Res\" />
  </ItemGroup>
</Project>