<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.HWorkspace.Page" Version="0.8.1--0002-develop" />
    <PackageReference Include="CK.SqlServer.Dapper" Version="11.1.1--0002-develop" />
    <PackageReference Include="CK.Ng.AspNet.Auth" Version="0.25.1--0003-develop" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.IO.Ng.SiteMap\CK.IO.Ng.SiteMap.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Res\" />
  </ItemGroup>
</Project>